// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCES3xbu5ojiRaeH8b-swFQY6se4Sk3CeA',
    appId: '1:404054505050:web:d9ffbf95fae069a8de8a63',
    messagingSenderId: '404054505050',
    projectId: 'chatapp-83614',
    authDomain: 'chatapp-83614.firebaseapp.com',
    storageBucket: 'chatapp-83614.firebasestorage.app',
    measurementId: 'G-KR63QGQS6R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLdkrrhx9Hx__-uY1MCQ9bQ6c5Ux4H6Qo',
    appId: '1:404054505050:android:a7e1a8081d99873bde8a63',
    messagingSenderId: '404054505050',
    projectId: 'chatapp-83614',
    storageBucket: 'chatapp-83614.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxfcpD9mTauzDk9ocxfnPcSlEDUVnFAcc',
    appId: '1:404054505050:ios:7df5ea0dd1c5fd73de8a63',
    messagingSenderId: '404054505050',
    projectId: 'chatapp-83614',
    storageBucket: 'chatapp-83614.firebasestorage.app',
    iosBundleId: 'com.example.parking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxfcpD9mTauzDk9ocxfnPcSlEDUVnFAcc',
    appId: '1:404054505050:ios:7df5ea0dd1c5fd73de8a63',
    messagingSenderId: '404054505050',
    projectId: 'chatapp-83614',
    storageBucket: 'chatapp-83614.firebasestorage.app',
    iosBundleId: 'com.example.parking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCES3xbu5ojiRaeH8b-swFQY6se4Sk3CeA',
    appId: '1:404054505050:web:30cf09ac90f64982de8a63',
    messagingSenderId: '404054505050',
    projectId: 'chatapp-83614',
    authDomain: 'chatapp-83614.firebaseapp.com',
    storageBucket: 'chatapp-83614.firebasestorage.app',
    measurementId: 'G-9S7CTSV3GM',
  );
}
